services:
  - type: web
    name: loan-eligibility-predictor
    runtime: node
    buildCommand: pip install -r requirements.txt && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free